-- Expand solicitudes table with full intake form fields
ALTER TABLE solicitudes
  DROP COLUMN IF EXISTS tiene_otros_animales,
  DROP COLUMN IF EXISTS tiene_jardin,
  ADD COLUMN IF NOT EXISTS edad text,
  ADD COLUMN IF NOT EXISTS ocupacion text,
  ADD COLUMN IF NOT EXISTS tipo_vivienda text,
  ADD COLUMN IF NOT EXISTS tipo_vivienda_otro text,
  ADD COLUMN IF NOT EXISTS vivienda_es text,
  ADD COLUMN IF NOT EXISTS alquiler_permite_mascotas text,
  ADD COLUMN IF NOT EXISTS donde_estara_perrito text,
  ADD COLUMN IF NOT EXISTS patio_verjado text,
  ADD COLUMN IF NOT EXISTS horas_solo text,
  ADD COLUMN IF NOT EXISTS que_ocurrira_si_mudas text,
  ADD COLUMN IF NOT EXISTS personas_en_hogar text,
  ADD COLUMN IF NOT EXISTS hay_ninos_edades text,
  ADD COLUMN IF NOT EXISTS todos_de_acuerdo text,
  ADD COLUMN IF NOT EXISTS alguien_alergico text,
  ADD COLUMN IF NOT EXISTS ha_tenido_perros text,
  ADD COLUMN IF NOT EXISTS que_ocurrio_con_ellos text,
  ADD COLUMN IF NOT EXISTS tiene_otras_mascotas text,
  ADD COLUMN IF NOT EXISTS mascotas_esterilizadas text,
  ADD COLUMN IF NOT EXISTS tiene_veterinario text,
  ADD COLUMN IF NOT EXISTS dispuesto_gastos_vet text,
  ADD COLUMN IF NOT EXISTS donde_dormira_perro text,
  ADD COLUMN IF NOT EXISTS que_haria_conducta text,
  ADD COLUMN IF NOT EXISTS que_haria_no_puede text,
  ADD COLUMN IF NOT EXISTS motivo_no_podria text,
  ADD COLUMN IF NOT EXISTS consciente_necesidades boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS consciente_responsabilidad text,
  ADD COLUMN IF NOT EXISTS cualidades_buscadas text,
  ADD COLUMN IF NOT EXISTS algo_mas text;
